### ISSUE TITLE
filmulator occupies one core when import-tab is active

### ISSUE THREAD

**Issue by heckflosse** [CarVac/filmulator-gui#103]
On my 8-core, cpu-load when filmulator import tab is active, is 12%, means it fully uses one core to do nothing (except from the weird animation below Source Directory and Destination Directory)

**Comment by CarVac** [comment]
![Screenshot_20190623_162851](https://user-images.githubusercontent.com/4342361/59981616-fd311080-95d3-11e9-842f-aac8e733f78b.png)

This doesn't happen for me on Linux. It uses a fraction of one core (100% is one full core; when actually processing it goes to >1200%).

This might be something Windows-related, because the UI is overall less smooth-running on my laptop.

**Comment by heckflosse** [comment]
@CarVac That only happens when import-tab is active. When other tabs are active, cpu-load is 0%

**Comment by gaaned92** [comment]
on my pc  Intel i76700K with HD graphics 530
When import tab active it takes 0,4% CPU and 13,5%GPU
In Filmulate tab with displayed image, and modifying nothing, 0-0,1%CPU, 0% GPU
