### ISSUE TITLE
Feature: White balance picker

### ISSUE THREAD

**Issue by drewhk** [CarVac/filmulator-gui#125]
It would be nice to have a "picker" tool to select a white/gray region/spot in the image and have the white balance adjusted automatically using that region/spot.

**Comment by mberg2007** [comment]
I second this proposal. The manual controls allow you to get the job done, but having a grey area picker would be so much easier.

**Comment by CarVac** [comment]
Just replying to say that the feature is in progress.

It's going to store the custom sampled WB setting and apply it to other images taken by the same camera model.

**Comment by CarVac** [comment]
The feature is done as of this commit: https://github.com/CarVac/filmulator-gui/commit/23d5012ce5f40be5762a48e590029b099840072d

Nightly builds are up on discuss.pixls.us as 0.11.1rc8.

https://discuss.pixls.us/t/filmulator-nightly-builds-now-for-windows-and-linux/12838

**Comment by mbetrifork** [comment]
I just downloaded 0.11.1rc8 and gave it a try. It works as expected and is a great addition to Filmulator I think. Thanks for taking time to continue to improve on the program :-)

However can I ask if the WB picker itself bases its evaluation on a single pixel? Or is in an average of the little "square" at the center of the crosshairs?

Many programs allow the user to pick an area, in order to avoid accidently selecting a pixel that has some chromatic abberation or color noise. If the selection is currently for a single pixel I would suggest adding an "area selector" as well.

**Comment by CarVac** [comment]
I wouldn't have made the UI draw a square if it didn't sample from the whole square :)

It's 21x21 pixels, and if it overhangs the edge of the image then it only averages the part that's in-frame.
