### ISSUE TITLE
check for lens correction updates and Update lens correction database

### ISSUE THREAD

**Issue by vince0708** [CarVac/filmulator-gui#149]
When i click on check for lens correction updates it cant be updated. Message: Database unavailable from server.
When i click on update for lens correction database it cant be updated. Message is: unavailable from server.

Is there a way to solve it?

I have tried Filmulator_v0.11.1.AppImage, Filmulator_v0.11.2rc11.AppImage and the flatpack package 0.11.1. 
Zorin OS 16.2

**Comment by CarVac** [comment]
The Lensfun project changed their website. I'm looking into grabbing the lens correction data straight from GitHub since I cannot seem to find the new location.

**Comment by vince0708** [comment]
Oke, thanks for your reply.

**Comment by koehlerson** [comment]
I just want to note +1 for this, since I installed fimulator for the first time. Thanks for the effort!

**Comment by noelbautista91** [comment]
+1. Would it be possible to add a slider for people who have lenses not in Lensfun?

**Comment by geni1105** [comment]
Took me a couple of hours to find out - the new location is at https://wilson.bronger.org/lensfun-db/ 

The change in lensfun-dbupdate.cpp is of course trivial, but if you prefer I can try to create a pull request.

(Just fell in love with Filmulator again, and did a bit of polishing on my local MacOs build ;-) )

**Comment by CarVac** [comment]
Oh I'm soooo dumb, that was right there in the code commented out as an "alternate" and I never thought to try it...

**Comment by cirrusflyer** [comment]
I'm not sure where to make the fix in Filmulator to address this location change of the lensfun database.  Can someone provide some rough instructions?

**Comment by geni1105** [comment]
You would need to change the old URL (http://lensfun.sourceforge.net/db/) to the new one (https://wilson.bronger.org/lensfun-db/) in lensfun-dbupdate.cpp and build Filmulator anew yourself.
Unfortunately the new URL is longer than the old one, so just patching the binary instead of rebuilding is not possible. 

If you happen to be on MacOs, an updated version of Filmulator is here https://www.dropbox.com/sh/gheb112zfcfcyyi/AAD0Lxh3d6QTN5UPtO4HiAQAa?dl=0  
It also has changes for MacOS (enable "Open with ..." and a fix to prevent crashes with noise reduction).

**Comment by cirrusflyer** [comment]
Thanks.  I'm running on Zorin OS - Ubuntu.  I"ll take a look.

**Comment by CarVac** [comment]
fixed in https://github.com/CarVac/filmulator-gui/commit/dec02c29622c14b711e8ff44a79660bc1573993c
