### ISSUE TITLE
Feature request: open raws without need for import

### ISSUE THREAD

**Issue by Beep6581** [CarVac/filmulator-gui#37]
I would like to be able to open raws without needing to "import" them first.

**Comment by CarVac** [comment]
Would "import in place" where it doesn't move (or back up) the file be sufficient? I've been trying to figure out the best UI design for this, which is why it's not implemented yet.

(I was going to have buttons above the import settings boxes which would let you select between "Import from card", "Import from backup", and "Import in place" which would switch between different displayed settings boxes)

**Comment by Beep6581** [comment]
I don't mind having the program scan the images if that makes certain operations easier.

Why does the program want to back images up - it doesn't edit the raw files in any way, does it?

**Comment by CarVac** [comment]
Ok, I'll put import-in-place next in the priority queue for once I sort out the Qt 5.5 compatibility issues which are currently being a major pain in the butt.

Regarding backups: I have it back up images so I don't have to copy them manually.

It's for data redundancy purposes. You can e.g. set it to a network drive to get better redundancy, for example.

**Comment by CarVac** [comment]
I've finally, finally completed import-in-place. Only took me 11 months... https://github.com/CarVac/filmulator-gui/commit/defa6609409e1835dcd56e362e8f6ea6fc22d3c4

I'll leave the issue open until I've tested it enough to be comfortable merging it into master.

**Comment by CarVac** [comment]
It's in master now.

**Comment by Beep6581** [comment]
I won't have time to test in the near future, but it's good to have such a feature :+1:
