### ISSUE TITLE
Allow input of more precise values

### ISSUE THREAD

**Issue by mbaz** [CarVac/filmulator-gui#62]
It can be hard to get a specific value using the sliders. Consider adding text input (so the user can type in a specific value) or using a key modifier to slow down the slider.

**Comment by CarVac** [comment]
You can stretch the width of the tools and that will double the precision with which you can select.

Additionally, in the Settings tab you can raise the overall UI scale of the program and that will allow you to choose more finely (though it'll make everything bigger as well; it's good for high DPI screens).

---

I'll look into implementing one of your other suggestions, though.

**Comment by mbaz** [comment]
The downside of stretching the toolbar is that then the image preview area is made smaller. This can be a problem when working on a smallish screen.

**Comment by CarVac** [comment]
Fixed in https://github.com/CarVac/filmulator-gui/commit/777542a12f36a8f5eec509d2b07663839dbfb918

The spinner is revealed and hidden by right-clicking on the tool name of any tool that has a continuous (non-stepped) slider.

Drag beginning anywhere in the circle (including the inner circle) to precisely control the tool. Clockwise will move the slider to the right, while counterclockwise will move the slider to the left. Eight full revolutions will equal the full range of the slider.

You don't have to end the drag in the circle; indeed you can get incredible precision of adjustment by dragging far away from the circle.

**Comment by mbaz** [comment]
This sounds like a great solution; thanks!
